const { Gtk, Gio, GLib } = imports.gi;
function setText(view,text){view.get_buffer().set_text(String(text||""),-1);}
function category(name){const e=(name.includes(".")?name.split(".").pop():"").toLowerCase();if(["png","jpg","jpeg","gif","webp","svg"].includes(e))return"Images";if(["mp4","mkv","mov","webm","avi"].includes(e))return"Videos";if(["mp3","wav","ogg","flac","m4a"].includes(e))return"Audio";if(["pdf","doc","docx","odt","txt","md","rtf"].includes(e))return"Documents";if(["zip","tar","gz","bz2","xz","7z","rar"].includes(e))return"Archives";if(["js","ts","py","java","kt","c","cpp","h","rs","go","lua","sh","html","css","json","xml","yml","yaml"].includes(e))return"Code";return"Other";}
function createPage(ctx,entry){const{common,window}=ctx;const s=new Gtk.ScrolledWindow({hexpand:true,vexpand:true});const p=new Gtk.Box({orientation:Gtk.Orientation.VERTICAL,spacing:12,hexpand:true});p.set_margin_top(24);p.set_margin_bottom(24);p.set_margin_start(28);p.set_margin_end(28);p.append(common.pageTitle(entry.name));p.append(common.infoLabel("Preview first, then organize top-level files by type. Undo restores the last run."));const c=common.card();const folderLabel=common.infoLabel("No folder selected");const row=new Gtk.Box({orientation:Gtk.Orientation.HORIZONTAL,spacing:8});const choose=new Gtk.Button({label:"Choose Folder"});choose.add_css_class("primary");const preview=new Gtk.Button({label:"Preview"});const organize=new Gtk.Button({label:"Organize"});const undo=new Gtk.Button({label:"Undo Last Run"});[choose,preview,organize,undo].forEach(b=>row.append(b));c.append(folderLabel);c.append(row);p.append(c);const out=new Gtk.TextView({editable:false,monospace:true,wrap_mode:Gtk.WrapMode.WORD_CHAR,vexpand:true});const os=new Gtk.ScrolledWindow({min_content_height:430,vexpand:true});os.set_child(out);p.append(os);s.set_child(p);let folder=null,moves=[];
function list(){const a=[];if(!folder)return a;try{const d=GLib.Dir.open(folder,0);let n;while((n=d.read_name())!==null){const path=GLib.build_filenamev([folder,n]);if(GLib.file_test(path,GLib.FileTest.IS_REGULAR))a.push({name:n,path,cat:category(n)});}}catch(e){setText(out,e.message);}return a;}
function show(){if(!folder){setText(out,"Choose a folder first.");return;}const a=list();setText(out,a.length?a.map(x=>`${x.name} -> ${x.cat}/`).join("\n"):"No top-level files found.");}
function destFor(item){const d=GLib.build_filenamev([folder,item.cat]);GLib.mkdir_with_parents(d,0o755);let target=GLib.build_filenamev([d,item.name]);if(!GLib.file_test(target,GLib.FileTest.EXISTS))return target;const dot=item.name.lastIndexOf("."),base=dot>0?item.name.slice(0,dot):item.name,ext=dot>0?item.name.slice(dot):"";let i=1;while(GLib.file_test(target,GLib.FileTest.EXISTS))target=GLib.build_filenamev([d,`${base}_${i++}${ext}`]);return target;}
choose.connect("clicked",()=>{const d=new Gtk.FileChooserNative({title:"Choose Folder",transient_for:window,action:Gtk.FileChooserAction.SELECT_FOLDER,accept_label:"Choose",cancel_label:"Cancel"});d.connect("response",(_,r)=>{if(r===Gtk.ResponseType.ACCEPT){const f=d.get_file();folder=f?f.get_path():null;if(folder){folderLabel.set_label(folder);show();}}d.destroy();});d.show();});preview.connect("clicked",show);organize.connect("clicked",()=>{if(!folder)return show();moves=[];const logs=[];for(const item of list()){const to=destFor(item);try{Gio.File.new_for_path(item.path).move(Gio.File.new_for_path(to),Gio.FileCopyFlags.NONE,null,null);moves.push({from:item.path,to});logs.push(`${item.name} -> ${item.cat}/`);}catch(e){logs.push(`FAILED ${item.name}: ${e.message}`);}}setText(out,logs.join("\n")||"Nothing to organize.");});undo.connect("clicked",()=>{if(!moves.length){setText(out,"Nothing to undo.");return;}const logs=[];for(const m of [...moves].reverse()){try{Gio.File.new_for_path(m.to).move(Gio.File.new_for_path(m.from),Gio.FileCopyFlags.NONE,null,null);logs.push(`Restored ${GLib.path_get_basename(m.from)}`);}catch(e){logs.push(`FAILED: ${e.message}`);}}moves=[];setText(out,logs.join("\n"));});return s;}
var metadata={id:"organizer",name:"File Organizer",icon:"📁"};
